import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('pz_commands', (table) => {
    table.increments('id').primary();
    table.integer('tenant_id').nullable().references('id').inTable('tenants').onDelete('CASCADE');
    table.string('name', 100).notNullable();
    table.string('label', 200).notNullable();
    table.text('description').nullable();
    table.string('category', 50).notNullable().defaultTo('geral');
    table.string('command_template', 500).notNullable();
    table.jsonb('params').notNullable().defaultTo('[]');
    table.boolean('is_dangerous').notNullable().defaultTo(false);
    table.timestamps(true, true);
  });

  // Seed all built-in PZ commands (tenant_id = null = shared/read-only)
  await knex('pz_commands').insert([
    // === INFO ===
    { tenant_id: null, name: 'players', label: 'Listar Jogadores', description: 'Lista todos os jogadores conectados no servidor.', category: 'info', command_template: 'players', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'showoptions', label: 'Ver Opções do Servidor', description: 'Exibe a lista de opções atuais do servidor com seus valores.', category: 'info', command_template: 'showoptions', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'help', label: 'Ajuda', description: 'Exibe a lista de todos os comandos admin disponíveis.', category: 'info', command_template: 'help', params: JSON.stringify([]), is_dangerous: false },
    // === JOGADORES ===
    { tenant_id: null, name: 'additem', label: 'Dar Item', description: 'Dá um item a um jogador. Count é opcional (padrão: 1).', category: 'jogadores', command_template: 'additem "{username}" {item} {count}', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'item', label: 'Item (módulo.item)', type: 'text', required: true, placeholder: 'Base.Axe' }, { name: 'count', label: 'Quantidade', type: 'number', required: false, placeholder: '1', default: '1' }]), is_dangerous: false },
    { tenant_id: null, name: 'addxp', label: 'Dar XP', description: 'Dá pontos de experiência a um jogador em uma habilidade específica.', category: 'jogadores', command_template: 'addxp "{username}" {perk}={xp}', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'perk', label: 'Habilidade', type: 'text', required: true, placeholder: 'Woodwork' }, { name: 'xp', label: 'Quantidade de XP', type: 'number', required: true, placeholder: '100' }]), is_dangerous: false },
    { tenant_id: null, name: 'addvehicle', label: 'Spawnar Veículo', description: 'Spawna um veículo próximo a um jogador.', category: 'jogadores', command_template: 'addvehicle {vehicle} "{username}"', params: JSON.stringify([{ name: 'vehicle', label: 'Veículo (script)', type: 'text', required: true, placeholder: 'Base.VanAmbulance' }, { name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }]), is_dangerous: false },
    { tenant_id: null, name: 'godmode', label: 'Modo Deus', description: 'Torna um jogador invencível (sem receber dano).', category: 'jogadores', command_template: 'godmode "{username}" -{value}', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'value', label: 'Ativar / Desativar', type: 'select', required: true, options: ['true', 'false'] }]), is_dangerous: false },
    { tenant_id: null, name: 'invisible', label: 'Invisibilidade', description: 'Torna um jogador invisível para zumbis.', category: 'jogadores', command_template: 'invisible "{username}" -{value}', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'value', label: 'Ativar / Desativar', type: 'select', required: true, options: ['true', 'false'] }]), is_dangerous: false },
    { tenant_id: null, name: 'noclip', label: 'Noclip', description: 'Permite ao jogador atravessar paredes e estruturas.', category: 'jogadores', command_template: 'noclip "{username}" -{value}', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'value', label: 'Ativar / Desativar', type: 'select', required: true, options: ['true', 'false'] }]), is_dangerous: false },
    { tenant_id: null, name: 'teleport', label: 'Teleportar para Jogador', description: 'Teleporta player1 até player2. Se player2 omitido, teleporta admin até player1.', category: 'jogadores', command_template: 'teleport "{player1}" "{player2}"', params: JSON.stringify([{ name: 'player1', label: 'Jogador (a mover)', type: 'text', required: true, placeholder: 'rj' }, { name: 'player2', label: 'Destino (jogador)', type: 'text', required: false, placeholder: 'toUser' }]), is_dangerous: false },
    { tenant_id: null, name: 'teleportto', label: 'Teleportar para Coordenadas', description: 'Teleporta para coordenadas X,Y,Z específicas.', category: 'jogadores', command_template: 'teleportto {x},{y},{z}', params: JSON.stringify([{ name: 'x', label: 'Coordenada X', type: 'number', required: true, placeholder: '100098' }, { name: 'y', label: 'Coordenada Y', type: 'number', required: true, placeholder: '189980' }, { name: 'z', label: 'Coordenada Z', type: 'number', required: false, placeholder: '0', default: '0' }]), is_dangerous: false },
    { tenant_id: null, name: 'kickuser', label: 'Kickar Jogador', description: 'Expulsa um jogador do servidor com motivo opcional.', category: 'jogadores', command_template: 'kickuser "{username}" -r "{reason}"', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'reason', label: 'Motivo', type: 'text', required: false, placeholder: 'Comportamento inadequado' }]), is_dangerous: true },
    { tenant_id: null, name: 'banuser', label: 'Banir Jogador', description: 'Bane um jogador do servidor com motivo opcional.', category: 'jogadores', command_template: 'banuser "{username}" -r "{reason}"', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'reason', label: 'Motivo do Ban', type: 'text', required: false, placeholder: 'Motivo do ban' }]), is_dangerous: true },
    { tenant_id: null, name: 'unbanuser', label: 'Desbanir Jogador', description: 'Remove o ban de um jogador pelo username.', category: 'jogadores', command_template: 'unbanuser "{username}"', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }]), is_dangerous: false },
    { tenant_id: null, name: 'banid', label: 'Banir por SteamID', description: 'Bane um jogador pelo SteamID da Steam.', category: 'jogadores', command_template: 'banid {steamid}', params: JSON.stringify([{ name: 'steamid', label: 'SteamID', type: 'text', required: true, placeholder: '76561198000000000' }]), is_dangerous: true },
    { tenant_id: null, name: 'unbanid', label: 'Desbanir por SteamID', description: 'Remove o ban de um SteamID da Steam.', category: 'jogadores', command_template: 'unbanid {steamid}', params: JSON.stringify([{ name: 'steamid', label: 'SteamID', type: 'text', required: true, placeholder: '76561198000000000' }]), is_dangerous: false },
    { tenant_id: null, name: 'setaccesslevel', label: 'Definir Nível de Acesso', description: 'Define o nível de acesso de um jogador. Use "none" para remover qualquer nível.', category: 'jogadores', command_template: 'setaccesslevel "{username}" {level}', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'level', label: 'Nível de Acesso', type: 'select', required: true, options: ['admin', 'moderator', 'overseer', 'gm', 'observer', 'none'] }]), is_dangerous: false },
    { tenant_id: null, name: 'adduser', label: 'Adicionar Usuário', description: 'Adiciona um novo usuário ao servidor whitelistado.', category: 'jogadores', command_template: 'adduser "{username}" "{password}"', params: JSON.stringify([{ name: 'username', label: 'Username', type: 'text', required: true, placeholder: 'rj' }, { name: 'password', label: 'Senha', type: 'text', required: true, placeholder: '12345' }]), is_dangerous: false },
    { tenant_id: null, name: 'addusertowhitelist', label: 'Adicionar à Whitelist', description: 'Adiciona um usuário conectado com senha à whitelist.', category: 'jogadores', command_template: 'addusertowhitelist "{username}"', params: JSON.stringify([{ name: 'username', label: 'Username', type: 'text', required: true, placeholder: 'rj' }]), is_dangerous: false },
    { tenant_id: null, name: 'addalltowhitelist', label: 'Todos para Whitelist', description: 'Adiciona todos os usuários conectados com senha à whitelist.', category: 'jogadores', command_template: 'addalltowhitelist', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'removeuserfromwhitelist', label: 'Remover da Whitelist', description: 'Remove um usuário da whitelist.', category: 'jogadores', command_template: 'removeuserfromwhitelist "{username}"', params: JSON.stringify([{ name: 'username', label: 'Username', type: 'text', required: true, placeholder: 'rj' }]), is_dangerous: false },
    { tenant_id: null, name: 'voiceban', label: 'Banir Voz', description: 'Bloqueia ou desbloqueia a voz de um jogador.', category: 'jogadores', command_template: 'voiceban "{username}" -{value}', params: JSON.stringify([{ name: 'username', label: 'Username do Jogador', type: 'text', required: true, placeholder: 'rj' }, { name: 'value', label: 'Bloquear / Desbloquear', type: 'select', required: true, options: ['true', 'false'] }]), is_dangerous: false },
    // === SERVIDOR ===
    { tenant_id: null, name: 'servermsg', label: 'Broadcast (Mensagem Global)', description: 'Envia uma mensagem para todos os jogadores conectados.', category: 'servidor', command_template: 'servermsg "{message}"', params: JSON.stringify([{ name: 'message', label: 'Mensagem', type: 'text', required: true, placeholder: 'O servidor será reiniciado em 5 minutos!' }]), is_dangerous: false },
    { tenant_id: null, name: 'save', label: 'Salvar Mundo', description: 'Salva o estado atual do mundo no servidor.', category: 'servidor', command_template: 'save', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'reloadoptions', label: 'Recarregar Opções', description: 'Recarrega as opções do servidor e envia aos clientes conectados.', category: 'servidor', command_template: 'reloadoptions', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'changeoption', label: 'Alterar Opção do Servidor', description: 'Altera uma opção específica do servidor em tempo real.', category: 'servidor', command_template: 'changeoption {option} "{value}"', params: JSON.stringify([{ name: 'option', label: 'Nome da Opção', type: 'text', required: true, placeholder: 'SleepAllowed' }, { name: 'value', label: 'Novo Valor', type: 'text', required: true, placeholder: 'true' }]), is_dangerous: false },
    { tenant_id: null, name: 'reloadlua', label: 'Recarregar Lua', description: 'Recarrega um script Lua específico.', category: 'servidor', command_template: 'reloadlua "{filename}"', params: JSON.stringify([{ name: 'filename', label: 'Nome do Arquivo', type: 'text', required: true, placeholder: 'MyScript.lua' }]), is_dangerous: false },
    { tenant_id: null, name: 'sendpulse', label: 'Toggle Server Pulse', description: 'Alterna o envio de informações de performance do servidor para este cliente.', category: 'servidor', command_template: 'sendpulse', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'quit', label: 'Desligar Servidor', description: 'Salva o mundo e desliga o servidor. AÇÃO IRREVERSÍVEL.', category: 'servidor', command_template: 'quit', params: JSON.stringify([]), is_dangerous: true },
    // === EVENTOS ===
    { tenant_id: null, name: 'startrain', label: 'Iniciar Chuva', description: 'Inicia a chuva no servidor.', category: 'eventos', command_template: 'startrain', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'stoprain', label: 'Parar Chuva', description: 'Para a chuva no servidor.', category: 'eventos', command_template: 'stoprain', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'chopper', label: 'Evento Helicóptero', description: 'Coloca um evento de helicóptero em um jogador aleatório.', category: 'eventos', command_template: 'chopper', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'gunshot', label: 'Evento Tiro', description: 'Coloca sons de tiro próximos a um jogador aleatório.', category: 'eventos', command_template: 'gunshot', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'alarm', label: 'Alarme de Prédio', description: 'Ativa um alarme de prédio na posição do admin. (Deve estar dentro de um cômodo.)', category: 'eventos', command_template: 'alarm', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'createhorde', label: 'Criar Horda de Zumbis', description: 'Spawna uma horda de zumbis próxima a um jogador.', category: 'eventos', command_template: 'createhorde {count} "{username}"', params: JSON.stringify([{ name: 'count', label: 'Quantidade de Zumbis', type: 'number', required: true, placeholder: '150' }, { name: 'username', label: 'Username do Jogador', type: 'text', required: false, placeholder: 'rj' }]), is_dangerous: false },
    { tenant_id: null, name: 'removezombies', label: 'Remover Zumbis', description: 'Remove todos os zumbis do servidor.', category: 'eventos', command_template: 'removezombies', params: JSON.stringify([]), is_dangerous: false },
    { tenant_id: null, name: 'releasesafehouse', label: 'Liberar Safehouse', description: 'Libera uma safehouse que o admin possui.', category: 'eventos', command_template: 'releasesafehouse', params: JSON.stringify([]), is_dangerous: false },
  ]);
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('pz_commands');
}
